package personalFinanceTracker;

public enum Category {

	FOOD, TRANSPORTATION, UTILITIES, ENTERTAINMENT, HEALTHCARE, EDUCATION, PERSONAL_CARE, MISCELLANEOUS, RENT, SALARY, BUSINESS, INVESTMENTS, BILLS
}
